version: "3.5"
services:
  snipe-it:
    image: lscr.io/linuxserver/snipe-it:latest
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy
      - traefik.http.routers.${SERVICE}.entrypoints=https
      - traefik.http.routers.${SERVICE}.rule=Host(`${URL}`)
      - traefik.http.services.${SERVICE}-service.loadbalancer.server.port=${PORT}
      - traefik.http.services.${SERVICE}-service.loadbalancer.server.scheme=http
      - traefik.http.services.${SERVICE}-service.loadbalancer.sticky.cookie=true
      - traefik.http.services.${SERVICE}-service.loadbalancer.sticky.cookie.httponly=true
      - traefik.http.services.${SERVICE}-service.loadbalancer.sticky.cookie.secure=true
      - traefik.http.services.${SERVICE}-service.loadbalancer.sticky.cookie.samesite=strict
      - traefik.http.services.${SERVICE}-service.loadbalancer.sticky.cookie.name=${COOKIE}
      - traefik.http.routers.${SERVICE}.tls=true
      - traefik.http.routers.${SERVICE}.middlewares=secured-chain@file
    networks:
      - backend_mariadb
      - proxy
    environment:
      - PUID=${GID-1000}
      - PGID=${GID-1000}
      - APP_URL=https://${URL}
      - MYSQL_PORT_3306_TCP_ADDR=mariadb.docker
      - MYSQL_PORT_3306_TCP_PORT=3306
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - TZ=Africa/Johannesburg
      - MAIL_PORT_587_TCP_ADDR=${MAIL_PORT_587_TCP_ADDR}
      - MAIL_PORT_587_TCP_PORT=${MAIL_PORT_587_TCP_PORT}
      - MAIL_ENV_USERNAME=${MAIL_ENV_USERNAME}
      - MAIL_ENV_PASSWORD=${MAIL_ENV_PASSWORD}
      - MAIL_ENV_ENCRYPTION=${MAIL_ENV_ENCRYPTION}
      - MAIL_ENV_FROM_ADDR=${MAIL_ENV_FROM_ADDR}
      - MAIL_ENV_FROM_NAME=${MAIL_ENV_FROM_NAME}
    volumes:
      - snipeit-data:/config
    restart: unless-stopped

volumes:
  snipeit-data:
networks:
  backend_mariadb:
    external: true
  proxy:
    external: true