version: '3.9'

networks:
  traefik_proxy:
    name: traefik_proxy
    external: true
        
services:
  whoami:
    image: traefik/whoami
    container_name: whoami
    hostname: whoami
    restart: unless-stopped
    networks:
      traefik_proxy:
        aliases: 
          - docker.whoami.local
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik_proxy
      - traefik.http.routers.${SERVICE}.entrypoints=https
      - traefik.http.routers.${SERVICE}.rule=Host(`${URL}`)
      - traefik.http.services.${SERVICE}-service.loadbalancer.server.port=${PORT}
      - traefik.http.services.${SERVICE}-service.loadbalancer.server.scheme=http
      - traefik.http.services.${SERVICE}-service.loadbalancer.sticky.cookie=true
      - traefik.http.services.${SERVICE}-service.loadbalancer.sticky.cookie.httponly=true
      - traefik.http.services.${SERVICE}-service.loadbalancer.sticky.cookie.secure=true
      - traefik.http.services.${SERVICE}-service.loadbalancer.sticky.cookie.samesite=strict
      - traefik.http.services.${SERVICE}-service.loadbalancer.sticky.cookie.name=${COOKIE}
      - traefik.http.routers.${SERVICE}.tls=true
      - traefik.http.routers.${SERVICE}.middlewares=public-chain@file
