version: '3.8'
services:
  filebrowser:
    image: filebrowser/filebrowser
    container_name: filebrowser
    user: 84601239:84600513
    networks:
      - proxy
    ports:
      - 8081:80
    volumes:
      - ./data:/srv
      - ./filebrowser.db:/database.db
    restart: unless-stopped
    labels:
        - traefik.enable=true
        - traefik.docker.network=proxy
        - traefik.http.routers.${SERVICE}.entrypoints=https
        - traefik.http.routers.${SERVICE}.rule=Host(`${URL}`)
        - traefik.http.services.${SERVICE}-service.loadbalancer.server.port=${PORT}
        - traefik.http.services.${SERVICE}-service.loadbalancer.server.scheme=http
        - traefik.http.services.${SERVICE}-service.loadbalancer.sticky.cookie=true
        - traefik.http.services.${SERVICE}-service.loadbalancer.sticky.cookie.httponly=true
        - traefik.http.services.${SERVICE}-service.loadbalancer.sticky.cookie.secure=true
        - traefik.http.services.${SERVICE}-service.loadbalancer.sticky.cookie.samesite=strict
        - traefik.http.services.${SERVICE}-service.loadbalancer.sticky.cookie.name=${COOKIE}
        - traefik.http.routers.${SERVICE}.tls=true
        - traefik.http.routers.${SERVICE}.middlewares=secured-chain@file
    security_opt:
      - no-new-privileges:true
networks:
  proxy:
    external: true