version: "3.5"

networks:
  traefik_proxy:
    name: traefik_proxy
    external: true
  database_network:
    name: database_network
    external: true
  default:

volumes:
  zabbix-var:
  zabbix-usr:
  zabbix-snmptraps:
  zabbix-export:

x-shared:
  zabbix-service: &zabbix-service
    environment: &zabbix-environment
      DB_SERVER_HOST: ${DB_SERVER_HOST}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      ZBX_STARTJAVAPOLLERS: 5
      ZBX_STARTVMWARECOLLECTORS: 5
      ZBX_SERVER_HOST: zabbix-server-pgsql
      PHP_TZ: Africa/Johannesburg
    networks: &zabbix-network
      default:

services:
  zabbix-server-pgsql:
    image: zabbix/zabbix-server-pgsql:${VERSION}
    restart: unless-stopped
    container_name: zabbix-server-pgsql
    hostname: zabbix-server-pgsql
    networks:
      <<: *zabbix-network
        aliases:
          - zabbix-server
          - zabbix-server-pgsql
          - zabbix-server-ubuntu-pgsql
          - zabbix-server-pgsql-ubuntu
      database_network:
    ports:
      - "10051:10051"
    environment:
      <<: *zabbix-environment
      ZBX_HOSTNAME: zabbix-server-pgsql
      ZBX_STARTPINGERS: 20
      PHP_TZ: Africa/Johannesburg
    volumes:
      - zabbix-var:/var/lib/zabbix
      - zabbix-usr:/usr/lib/zabbix
      - /etc/localtime:/etc/localtime:ro
      - zabbix-export:/var/lib/zabbix/export
      - zabbix-snmptraps:/var/lib/zabbix/snmptraps
    labels:
      "com.centurylinklabs.watchtower.enable=true"
      "com.zabbix.description=Zabbix server with pgsql database support"
      "com.zabbix.company=Zabbix LLC"
      "com.zabbix.component=zabbix-server-pgsql"
      "com.zabbix.dbtype=pgsql"
      "com.zabbix.os=ubuntu"

  zabbix-agent2:
    image: zabbix/zabbix-agent2:${VERSION}
    restart: unless-stopped
    container_name: zabbix-agent2
    hostname: zabbix-agent2
    networks:
      <<: *zabbix-network
        aliases:
          - zabbix-agent2
    environment:
      <<: *zabbix-environment
      ZBX_HOSTNAME: zabbix-agent2
    volumes:
      - /etc/localtime:/etc/localtime:ro
    labels:
      "com.centurylinklabs.watchtower.enable=true"
      "com.zabbix.description=Zabbix agent2"
      "com.zabbix.company=Zabbix LLC"
      "com.zabbix.component=zabbix-agent2"
      "com.zabbix.dbtype=pgsql"
      "com.zabbix.os=ubuntu"

  zabbix-web-apache-pgsql:
    image: zabbix/zabbix-web-apache-pgsql:${VERSION}
    restart: unless-stopped
    container_name: zabbix-agent2
    hostname: zabbix-agent2
    networks:
      <<: *zabbix-network
      database_network:
      traefik_proxy:
        aliases:
          - docker.zabbix.local
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    environment:
      <<: *zabbix-environment
      ZBX_SERVER_NAME: Zabbix Container
      # ZBX_SSO_SP_CERT: /etc/zabbix/web/certs/sp.crt
      # ZBX_SSO_SP_KEY: /etc/zabbix/web/certs/sp.key
      # ZBX_SSO_IDP_CERT: /etc/zabbix/web/certs/idp.crt
      # ZBX_SSO_SETTINGS: {"strict":false, "baseurl":"https://zabbix.domain.com/", "use_proxy_headers":true}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      # - ./zabbix-img/icon-sprite.svg:/usr/share/zabbix/assets/img/icon-sprite.svg
      # - ./zabbix-certs:/etc/zabbix/web/certs
    depends_on:
     - zabbix-server-pgsql
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_proxy"
      - "traefik.http.routers.${TRAEFIK_SERVICE}.entrypoints=https"
      - "traefik.http.routers.${TRAEFIK_SERVICE}.rule=Host(`${TRAEFIK_URL}`)"
      - "traefik.http.services.${TRAEFIK_SERVICE}-service.loadbalancer.passhostheader=true"
      - "traefik.http.services.${TRAEFIK_SERVICE}-service.loadbalancer.server.port=${TRAEFIK_PORT}"
      - "traefik.http.services.${TRAEFIK_SERVICE}-service.loadbalancer.server.scheme=${TRAEFIK_SCHEME}"
      - "traefik.http.routers.${TRAEFIK_SERVICE}.tls=true"
      - "traefik.http.routers.${TRAEFIK_SERVICE}.middlewares=public-chain@file"
      - "com.zabbix.description:=Zabbix frontend on Nginx web-server with PostgreSQL database support"
      - "com.zabbix.company=Zabbix LLC"
      - "com.zabbix.component=zabbix-web-nginx-pgsql"
      - "com.zabbix.webserver=nginx"
      - "com.zabbix.dbtype=pgsql"
      - "com.zabbix.os=ubuntu"
