version: "3.5"

networks:
  traefik_proxy:
    name: traefik_proxy
    external: true
  default:
    ipam:
      driver: default
      config:
        - subnet: "172.31.8.0/24"

volumes:
  ntfy-cache:
  ntfy-etc:
  ntfy-lib:

services:
  ntfy:
    image: binwiederhier/ntfy
    command:
      - serve
    restart: always
    container_name: ntfy
    hostname: ntfy
    networks:
      default:
      traefik_proxy:
        aliases:
          - docker.ntfy.local
    healthcheck: # optional: remember to adapt the host:port to your environment
        test: ["CMD-SHELL", "wget -q --tries=1 http://localhost:80/v1/health -O - | grep -Eo '\"healthy\"\\s*:\\s*true' || exit 1"]
        interval: 60s
        timeout: 10s
        retries: 3
        start_period: 40s
    ports:
      - 8281:80
    environment:
      TZ: Africa/Johannesburg
    volumes:
      - ntfy-cache:/var/cache/ntfy
      - ntfy-etc:/etc/ntfy
      - ntfy-lib:/var/lib/ntfy
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_proxy"
      - "traefik.http.routers.${TRAEFIK_SERVICE}.entrypoints=https"
      - "traefik.http.routers.${TRAEFIK_SERVICE}.rule=Host(`${TRAEFIK_URL}`)"
      - "traefik.http.services.${TRAEFIK_SERVICE}-service.loadbalancer.passhostheader=true"
      - "traefik.http.services.${TRAEFIK_SERVICE}-service.loadbalancer.server.port=${TRAEFIK_PORT}"
      - "traefik.http.services.${TRAEFIK_SERVICE}-service.loadbalancer.server.scheme=${TRAEFIK_SCHEME}"
      - "traefik.http.routers.${TRAEFIK_SERVICE}.tls=true"
      - "traefik.http.routers.${TRAEFIK_SERVICE}.middlewares=public-chain@file"
