version: "3.5"

networks:
  traefik_proxy:
    name: traefik_proxy
    external: true
  database_network:
    name: database_network
    external: true
  default:

volumes:
  grafana-data:

services:
  grafana:
    image: grafana/grafana:10.1.6
    restart: unless-stopped
    container_name: grafana
    hostname: grafana
    networks:
      traefik_proxy:
        aliases:
          - docker.grafana.local
      database_network:
      default:
    env_file: .env
    volumes:
      - grafana-data:/var/lib/grafana
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_proxy"
      - "traefik.http.routers.${TRAEFIK_SERVICE}.entrypoints=https"
      - "traefik.http.routers.${TRAEFIK_SERVICE}.rule=Host(`${TRAEFIK_URL}`)"
      - "traefik.http.services.${TRAEFIK_SERVICE}-service.loadbalancer.passhostheader=true"
      - "traefik.http.services.${TRAEFIK_SERVICE}-service.loadbalancer.server.port=${TRAEFIK_PORT}"
      - "traefik.http.services.${TRAEFIK_SERVICE}-service.loadbalancer.server.scheme=${TRAEFIK_SCHEME}"
      - "traefik.http.routers.${TRAEFIK_SERVICE}.tls=true"
      - "traefik.http.routers.${TRAEFIK_SERVICE}.middlewares=public-chain@file"
