version: '3.9'

services:
  pgadmin:
    image: dpage/pgadmin4:latest
    networks:
      - proxy
      - backend_sql
    env_file: .env
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - './data:/var/lib/pgadmin'
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.${SERVICE}.entrypoints=https"
      - "traefik.http.routers.${SERVICE}.rule=Host(`${URL}`)"
      - "traefik.http.services.${SERVICE}-service.loadbalancer.passhostheader=true"
      - "traefik.http.services.${SERVICE}-service.loadbalancer.server.port=${PORT}"
      - "traefik.http.services.${SERVICE}-service.loadbalancer.server.scheme=${SCHEME}"
      - "traefik.http.routers.${SERVICE}.tls=true"
      - "traefik.http.routers.${SERVICE}.middlewares=secured-chain@file"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-O", "-", "http://localhost:80/misc/ping"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
networks:
  proxy:
    external: true
  backend_sql:
    external: true