FROM nginx:latest
COPY ./index.html /usr/share/nginx/html/index.html
ENV COMPANY_NAME=Acme Pty Ltd
ENV FONT_COLOR=#FFF
ENV COMPANY_LOGO=https://herdit.cloud/wp-content/uploads/2023/04/white-fill_orange-gradient_300x300.png
ENV BACKGROUND_COLOR=#d6433b