version: '3'
services:
  mailserver:
    image: docker.io/mailserver/docker-mailserver:latest
    container_name: mailserver
    hostname: mail
    domainname: ${DOMAIN}
    environment:
      - DMS_DEBUG=0
      - LOG_LEVEL=info
      - ONE_DIR=1
      - ENABLE_UPDATE_CHECK=1
      - UPDATE_CHECK_INTERVAL=1d
      - PERMIT_DOCKER=none
      - ENABLE_SRS=0
      - ENABLE_OPENDKIM=1
      - ENABLE_OPENDMARC=1
      - ENABLE_CLAMAV=1
      - ENABLE_RSPAMD=1
      - ENABLE_AMAVIS=1
      - AMAVIS_LOGLEVEL=1
      - ENABLE_DNSBL=1
      - ENABLE_FAIL2BAN=1
      - FAIL2BAN_BLOCKTYPE=drop
      - POSTSCREEN_ACTION=enforce
      - SSL_TYPE=letsencrypt
      - ENABLE_QUOTAS=1
      - LOGROTATE_INTERVAL=weekly
      - POSTFIX_INET_PROTOCOLS=all
      - DOVECOT_INET_PROTOCOLS=all
      - ENABLE_SPAMASSASSIN=1
      - SPAMASSASSIN_SPAM_TO_INBOX=1
      - ENABLE_SPAMASSASSIN_KAM=1
      - MOVE_SPAM_TO_JUNK=1
      - SA_TAG=2.0
      - SA_TAG2=6.31
      - SA_KILL=10.0
      - SA_SPAM_SUBJECT=***SPAM*****
      - ENABLE_FETCHMAIL=0
      - FETCHMAIL_POLL=300
      - DOVECOT_MAILBOX_FORMAT=maildir
      - ENABLE_POSTGREY=1
      - POSTGREY_DELAY=300
      - POSTGREY_MAX_AGE=35
      - POSTGREY_TEXT="Delayed by Postgrey"
      - POSTGREY_AUTO_WHITELIST_CLIENTS=5
      - ENABLE_SASLAUTHD=0
      - SRS_SENDER_CLASSES=envelope_sender
      - RELAY_PORT=25
      - RELAY_PASSWORD=
    ports:
      - "25:25"    # SMTP  (explicit TLS => STARTTLS)
      - "143:143"  # IMAP4 (explicit TLS => STARTTLS)
      - "465:465"  # ESMTP (implicit TLS)
      - "587:587"  # ESMTP (explicit TLS => STARTTLS)
      - "993:993"  # IMAP4 (implicit TLS)
    volumes:
      - mailserver-data/:/var/mail/
      - mailserver-state/:/var/mail-state/
      - mailserver-logs/:/var/log/mail/
      - mailserver-config/:/tmp/docker-mailserver/
      - mailserver-letsencrypt/letsencrypt:/etc/letsencrypt
      - /etc/localtime:/etc/localtime:ro
    restart: always
    stop_grace_period: 1m
    cap_add:
      - NET_ADMIN
    healthcheck:
      test: "ss --listening --tcp | grep -P 'LISTEN.+:smtp' || exit 1"
      timeout: 3s
      retries: 0

  certbot:
    image: certbot/certbot
    container_name: certbot
    ports:
      - "80:80"
    volumes: 
      - mailserver-letsencrypt:/etc/letsencrypt
      - mailserver-certbot-logs:/var/log/letsencrypt/
    command: ["certonly", "--standalone", "--force-renewal", "--email", "${EMAIL}", "-d", "mail.${DOMAIN}", "--agree-tos"]

volumes:
  mailserver-data:
  mailserver-state:
  mailserver-logs:
  mailserver-config:
  mailserver-letsencrypt:
  mailserver-certbot-logs: