version: '3.5'

services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    hostname: portainer
    restart: always
    networks:
      proxy:
        aliases:
          - docker.portainer.local
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.portainer.entrypoints=https"
      - "traefik.http.routers.portainer.rule=Host(`portainer.domain.com`)"
      - "traefik.http.services.portainer-service.loadbalancer.passhostheader=true"
      - "traefik.http.services.portainer-service.loadbalancer.server.port=9443"
      - "traefik.http.services.portainer-service.loadbalancer.server.scheme=https"
      - "traefik.http.routers.portainer.tls=true"
      - "traefik.http.routers.portainer.middlewares=public-chain@file"
    ports:
      - "9443:9443"
      - "8000:8000"
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
volumes:
  portainer_data:
networks:
  proxy:
    external: true
