---
###############################################################
#                   Authelia configuration                    #
###############################################################

server:
  host: 0.0.0.0
  port: 9091
log:
  level: debug
theme: grey
# This secret can also be set using the env variables AUTHELIA_JWT_SECRET_FILE randomly generated 64 char alphanumeric string
jwt_secret: b7bZikb46iovYJm5sX8XqtHcK96Ni77Fw7YByjYhgMTLLKRc34xbBvSkR3ahcEUd
default_redirection_url: https://login.auth.domain.com
totp:
  issuer: login.auth.domain.com

# duo_api:
#  hostname: api-123456789.example.com
#  integration_key: ABCDEF
#  # This secret can also be set using the env variables AUTHELIA_DUO_API_SECRET_KEY_FILE
#  secret_key: 1234567890abcdefghifjkl

authentication_backend:
  file:
    path: /config/users_database.yml
    password:
      algorithm: argon2id
      iterations: 1
      salt_length: 16
      parallelism: 8
      memory: 64

access_control:
  default_policy: deny
  rules:
    # Rules applied to everyone
    - domain: public.example.com
      policy: bypass
    - domain: traefik-dashboard.domain.com 
      policy: one_factor
      subject:
      - ['group:admins']
    # - domain: pve1.local.example.com
    #   policy: two_factor

session:
  name: authelia_session
  # This secret can also be set using the env variables AUTHELIA_SESSION_SECRET_FILE randomly generated 128 char alphanumeric string
  secret: rN3NyyDyoaQaZhZnRqoB3oUw9PZSyoEXEufFAz7xxd5osR66STjxr6vXUt2w8UDXriwF9X5idorwrniyBwbV4HrBvCKfh47quyVj3MrC8ceFYKuRpPgqQTinBy6HoA2x
  expiration: 3600  # 1 hour
  inactivity: 300  # 5 minutes
  domain: domain.com  # Should match whatever your root protected domain is

  # redis:
  #   host: redis
  #   port: 6379
  #   # This secret can also be set using the env variables AUTHELIA_SESSION_REDIS_PASSWORD_FILE
  #   # password: authelia

regulation:
  max_retries: 3
  find_time: 120
  ban_time: 300

storage:
  encryption_key: yK7PCLMjGFcksiX3aZGoy4xyJVk6iLk9MnmeuFMSWjG9m25acNJz4jJDahs39ZHX # Now required Random 65 char alphanumeric string
  local:
    path: /config/db.sqlite3

notifier:
  # smtp:
  #   host: smtp.domain.com
  #   port: 587
  #   timeout: 5s
  #   username: noreply@domain.com
  #   password: {your-password}
  #   sender: "Authelia <noreply@domain.com>"
  #   identifier: smtp.domain.com
  #   subject: "[Authelia] {title}"
  #   startup_check_address: noreply@domain.com
  #   disable_require_tls: false
  #   disable_starttls: false
  #   disable_html_emails: false
  #   tls:
  #     server_name: smtp.domain.com
  #     skip_verify: true
  #     minimum_version: TLS1.1
  #     maximum_version: TLS1.3
  #     certificate_chain: |
  #       -----BEGIN CERTIFICATE-----
  #       MIIDqj.....
  #       -----END CERTIFICATE-----
  #     private_key: |
  #       -----BEGIN PRIVATE KEY-----
  #       MIIEvQ.....
  #       -----END PRIVATE KEY-----


  filesystem:
    filename: /config/notification.txt

################################################################
#
# OpenID Connect 1.0
#
################################################################

identity_providers:
  oidc:
    issuer_certificate_chain: |
      -----BEGIN CERTIFICATE-----
      MIIDqj.....
      -----END CERTIFICATE-----
    issuer_private_key: |
      -----BEGIN PRIVATE KEY-----
      MIIEvQ.....
      -----END PRIVATE KEY-----
    access_token_lifespan: 1h
    authorize_code_lifespan: 1m
    id_token_lifespan: 1h
    refresh_token_lifespan: 90m
    enable_client_debug_messages: false
    enforce_pkce: public_clients_only
    cors:
      endpoints:
        - authorization
        - token
        - revocation
        - introspection
      allowed_origins:
        - "*"
      allowed_origins_from_client_redirect_uris: false
    ## The other portions of the mandatory OpenID Connect 1.0 configuration go here.
    ## See: https://www.authelia.com/c/oidc
    clients:
    - id: portainer
      description: Portainer
      secret: '$pbkdf2-sha512$.......long-key'
      public: false
      authorization_policy: one_factor
      redirect_uris:
        - https://portainer.domain.com
      scopes:
        - openid
        - profile
        - groups
        - email
      userinfo_signing_algorithm: none
    - id: jumpbox
      description: Jumpbox
      secret: '$pbkdf2-sha512$.......long-key'
      public: false
      authorization_policy: one_factor
      redirect_uris:
        - https://jumpbox.domain.com
      scopes:
        - openid
        - profile
        - groups
        - email
      response_types:
        - id_token
      grant_types:
        - implicit
      userinfo_signing_algorithm: none
    - id: grafana
      description: Grafana
      secret: '$pbkdf2-sha512$.......long-key'
      public: false
      authorization_policy: one_factor
      redirect_uris:
        - https://grafana.domain.com/login/generic_oauth
      scopes:
        - openid
        - profile
        - groups
        - email
      userinfo_signing_algorithm: none
    - id: wikijs
      description: WikiJS
      secret: '$pbkdf2-sha512$.......long-key'
      public: false
      authorization_policy: one_factor
      audience: []
      scopes:
        - openid
        - email
        - profile
      redirect_uris:
        - https://wiki.domain.com/login/n8asy1n5-0o3f-1fb6-f2dv-7ajf982nb03mg/callback
      userinfo_signing_algorithm: none
      response_modes:
        -  form_post