---
###############################################################
#                         Users Database                      #
###############################################################

# This file can be used if you do not have an LDAP set up.

# You can encrypt your password by running docker run authelia/authelia:latest authelia crypto hash generate argon2 --password 'password' and changing password to the password you want
# Digest: $argon2id$v=19$m=65536,t=3,p=4$Hjc8e7WYcBFcJmEDUOsS9A$ozM7RyZR1EyDR8cuyVpDDfmLrGPGFgo5E2NNqRumui4

# List of users
users:
  username@domain.com:
    displayname: "Local User"
    password: "$argon2id$v=19$m=65536,t=3,p=4$Hjc8e7WYcBFcJmEDUOsS9A$ozM7RyZR1EyDR8cuyVpDDfmLrGPGFgo5E2NNqRumui4" 
    email: username@domain.com
    groups:
      - admins

